<?php

/**
 * ProcessWire Module Template
 *
 * Demonstrates the Module interface and how to add hooks.
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ImagesManagerParser extends WireData implements Module {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {

        return array(
            'title' => 'Images Manager Parser',
            'version' => 4,
            'summary' => 'Add ImagesManager button to textarea fields defined in ImagesManager module, parses textarea to abstracts image tags saved in DB.',
            'href' => '',
            'author' => 'Soma',
            'singular' => true,
            'autoload' => true,
            'requires' => array('ImagesManager')
            );
    }


    public function init(){
        $options = $this->modules->getModuleConfigData('ImagesManager');
        $this->options = $options;

        // add hook to replace image tags to id tags and back
        if(strpos($_SERVER['REQUEST_URI'], $this->config->urls->admin) !== false){
            $this->addHookBefore('FieldtypeTextarea::wakeupValue', $this, 'wakeupValue');
            $this->addHookBefore('FieldtypeTextarea::sleepValue', $this, 'sleepValue');

            $this->addHookBefore('InputfieldTextarea::render', $this, 'addScripts');
            $this->addHookAfter('InputfieldTextarea::render', $this, 'addImagesManager');

        } else {
            $this->addHookAfter('Page::render', $this, 'renderPage');
        }
    }


    public function addScripts(HookEvent $event){
        $this->modules->get('ImagesManager');
        $this->modules->get('JqueryFancybox');
        $this->config->scripts->add($this->config->urls->ImagesManagerParser . 'ImagesManagerParser.js');
    }

    public function addImagesManager(HookEvent $event) {
        // add button to textarea fields
        $inputfield = $event->object;
        $fieldset = $event->return;

        if(!$this->user->isSuperuser() && !$this->user->hasPermission("images-manager")) return;

        // get text fields config
        if(!in_array($this->fields->get($inputfield->name)->id, $this->options['textareaFields'])) return;

        $href = $this->pages->get(2)->find('name=imagesmanager,include=all')->first()->url;
        $btn = $this->modules->get('InputfieldButton');
        $btn->href = $href;
        $btn->attr('id','imagesmanager_' . $inputfield->name);
        $btn->value = $this->_('Images Manager');
        $class = $btn->attr('class');
        $btn->attr('class', $class .' imagesmanager_fancybox');

        $event->return = str_replace($event->return, $btn->render() .'<br/>'. $event->return , $event->return);
    }

    public function wakeupValue(HookEvent $event) {

        // prevent execution (some conflicts) on field edit for tinymce textarea language fields
        if(wire('process') == 'ProcessField') return;

        $arguments = $event->arguments; // $page, $field, $value
        $value = $arguments[2];
        $field = $arguments[1];

        if(!in_array($field->id, $this->options['textareaFields'])) return;

        if(empty($value)) return;
        //if(!strlen($value)) return;

        if($value instanceof LanguagesPageFieldValue) {
            $value = $this->replaceLanguageValues($value);
        } else {
            $value = $this->parseTags($value);
        }

        if($this->config->debug) $this->message('FieldtypeTextarea (wakeupValue): ' . $arguments[0]->path . ': ' . $arguments[1]->name);

        $arguments[2] = $value;
        $event->arguments = $arguments;
    }

    public function sleepValue(HookEvent $event) {

        // prevent execution (some conflicts) on field edit for tinymce textarea language fields
        if(wire('process') == 'ProcessField') return;

        $arguments = $event->arguments;
        $value = $arguments[2];
        $field = $arguments[1];

        if(!in_array($field->id, $this->options['textareaFields'])) return;

        if(empty($value)) return;

        if($value instanceof LanguagesPageFieldValue) {
            $value = $this->replaceLanguageValues($value,false);
        } else {
            $value = $this->parseTags($value);
            $value = $this->parseImages($value);
        }

        // for debugging:
        if($this->config->debug) $this->message('FieldtypeTextarea (sleepValue): ' . $arguments[0]->path . ': ' . $arguments[1]->name);

        // stuff the value back in the arguments sent to the Fieldtype
        $arguments[2] = $value;
        $event->arguments = $arguments;
    }


    public function renderPage(HookEvent $event){
        $value = $event->return;
        $value = $this->parseTags($value);
        $event->return = $value;
    }

    public function ___parseTags($value){

        preg_match_all('#\{(image=.+?)\}#i', $value, $matches, PREG_SET_ORDER);

        if(count($matches)){

            foreach($matches as $match) {

                //print_r($match_parts);

                // to keep things easy and scalable we use PW selectors class
                $selectors = new Selectors($match[1]);

                $image_selector = $selectors->get('field=image');
                $imagepage = wire('pages')->get($image_selector->value);
                if(!$imagepage->id) continue;

                $imagepage->of(false);
                $image = $imagepage->get($this->options['imagesFieldName'])->first;
                $width_selector = $selectors->get('field=width');
                $height_selector = $selectors->get('field=height');
                $class_selector = $selectors->get('field=class');

                $width_attr = '';
                $height_attr = '';
                if($width_selector && $width_selector->value && $height_selector && $height_selector->value) {
                    $img = $image->size($width_selector->value, $height_selector->value)->url;
                    $width_attr = ' width="' . $width_selector->value . '"';
                    $height_attr = ' height="' . $height_selector->value . '"';
                } else if($width_selector && $width_selector->value) {
                    $img = $image->size($width_selector->value,0)->url;
                    $width_attr = ' width="' . $width_selector->value . '"';
                } else if($height_selector && $height_selector->value) {
                    $img = $image->size(0,$height_selector->value)->url;
                    $height_attr = ' height="' . $height_selector->value . '"';
                } else {
                    $img = $image->first->url;
                }


                $class_attr = '';
                if($class_selector && $class_selector->value){
                    $class_attr .= ' class="' . $class_selector->value . '"';
                }

                $rel_attr = '';
                $rel_selector = $selectors->get("field=rel");
                if($rel_selector && $rel_selector->value){
                    $rel_attr = ' rel="' . $rel_selector->value . '"';
                }

                $id_attr = '';
                $id_selector = $selectors->get("field=id");
                if($id_selector && $id_selector->value){
                    $id_attr = ' id="' . $id_selector->value . '"';
                }

                $alt_attr = '';
                if(strlen($image->description)){
                    $alt_attr = ' alt="' . $image->description . '"';
                } else if($descr = $imagepage->get($this->options['imagesDescriptionField'])){
                    $alt_attr = strlen($descr) ? ' alt="' . $descr . '"' : '';
                }

                $value = str_replace($match[0], '<img src="' . $img . '"' . $class_attr . $width_attr . $height_attr . $alt_attr . $id_attr . $rel_attr . '/>', $value);
            }
        }
        return $value;
    }


    public function ___replaceLanguageValues($value,$onlytags = true){

        $languages = $this->languages;

        foreach($languages as $lang) {
            $replaced_value = '';
            if($value == NULL) continue;

            // get the language value for parsing for page urls
            $replaced_value = $value->getLanguageValue($lang);
            if($onlytags){
                $replaced_value = $this->parseTags($replaced_value);
            } else {
                $replaced_value = $this->parseTags($replaced_value);
                $replaced_value = $this->parseImages($replaced_value);
            }

            // set the modified language value
            $value->setLanguageValue($lang,$replaced_value);
        }
        return $value;
    }


    public function ___parseImages($value){

        // replace extra whitespace coming from TinyMCE to avoid string replace issues
        $value = preg_replace("#([\"|\'])(\s+/>)#","$1/>",$value);

        $doc = new DOMDocument();
        $doc->formatOutput = false;
        $doc->preserveWhiteSpace = false;

        @$doc->loadHTML($value);

        $tags = $doc->getElementsByTagName('img');
        $replace = array();
        $with = array();

        foreach($tags as $tag) {
            $src = $tag->getAttribute('src');
            $width = $tag->getAttribute('width');
            $height = $tag->getAttribute('height');
            $class = $tag->getAttribute('class');
            $rel = $tag->getAttribute('rel');
            $id = $tag->getAttribute('id');

            if(strlen($src)){
                $path = pathinfo($src);
                $parts = explode("/",$path['dirname']);
                $pageid = $parts[count($parts)-1];
                $imagepage = $this->pages->get($pageid);

                if($imagepage->template == $this->options['imagesPageTemplate']){
                    $orig_tag = $doc->saveXML($tag);

                    $imagetag = "image=$pageid,";
                    $imagetag .= $width ? "width=$width," : "";
                    $imagetag .= $height ? "height=$height," : "";
                    $imagetag .= $class ? "class=$class," : '';
                    $imagetag .= $rel ? "rel=$rel," : '';
                    $imagetag .= $id ? "id=$id," : '';
                    $imagetag = "{". rtrim($imagetag,",") . "}";

                    $replace[] = $orig_tag;
                    $with[] = $imagetag;
                }
            }
        }
        if(!empty($replace)) $value = str_replace($replace, $with, $value);
        return $value;
    }

}
